trigger:
  - develop  # Runs when code is pushed to the develop branch

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: Terraform_Variables  # Import variables from the Azure DevOps library
- name: AZURE_SERVICE_CONNECTION
  value: 'AzureTerraformService'  # Azure DevOps Service Connection
- name: TF_WORKING_DIR
  value: 'infra/terraform'  # Path to Terraform files

stages:
  - stage: Terraform
    displayName: 'Terraform Deployment'
    jobs:
      - job: Terraform_Apply
        displayName: 'Terraform Init & Apply'
        steps:
          - checkout: self

          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.7.5'

          - script: |
              terraform init \
                -backend-config="storage_account_name=$(storageAccountName)" \
                -backend-config="container_name=$(containerName)" \
                -backend-config="key=$(key)" \
                -backend-config="access_key=$(accessKey)"
            workingDirectory: $(TF_WORKING_DIR)
            displayName: 'Terraform Init with Backend Config'

          - script: |
              terraform validate
            workingDirectory: $(TF_WORKING_DIR)
            displayName: 'Terraform Validate'

          - script: |
              terraform plan -out=tfplan
            workingDirectory: $(TF_WORKING_DIR)
            displayName: 'Terraform Plan'

          - script: |
              terraform apply -auto-approve tfplan
            workingDirectory: $(TF_WORKING_DIR)
            displayName: 'Terraform Apply'
