trigger:
  - develop  # Runs when code is pushed to develop branch

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: Terraform_Variables  # Load predefined variables from Azure DevOps Library
- name: AZURE_SERVICE_CONNECTION
  value: 'AzureTerraformService'
- name: TF_WORKING_DIR
  value: 'infra/terraform'
- name: RESOURCE_GROUP_NAME
  value: 'TerraformStateRG'

jobs:
  - job: TerraformInit
    displayName: 'Initialize Terraform'
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.7.5'  # Use your preferred Terraform version

      - task: TerraformTaskV4@4
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          backendServiceArm: $(AZURE_SERVICE_CONNECTION)
          backendAzureRmResourceGroupName: $(RESOURCE_GROUP_NAME)
          backendAzureRmStorageAccountName: $(storageAccountName)
          backendAzureRmContainerName: $(containerName)
          backendAzureRmKey: $(accessKey)
          command: 'init'
          workingDirectory: $(TF_WORKING_DIR)
          
      - task: TerraformTaskV4@4
        displayName: 'Terraform Validate'
        inputs:
         provider: 'azurerm'
         command: 'validate'
         workingDirectory: $(TF_WORKING_DIR)

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Terraform State'
        inputs:
          targetPath: $(TF_WORKING_DIR)
          artifactName: 'terraform-state'
